test

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -8,11 +8,9 @@ jobs:
     runs-on: windows-latest
 
     steps:
-        # Clone the current repository into /mod
+        # Clone the current repository
       - name: Checkout code
         uses: actions/checkout@v2
-        with: 
-            path: 'mod'
 
         # Clone AmethystAPI into /amethyst
       - name: Checkout Amethyst
@@ -21,57 +19,59 @@ jobs:
             repository: 'FrederoxDev/Amethyst'
             path: 'amethyst'
 
-    #   - name: Install deps with choco
-    #     run: |
-    #       choco install nasm -y
-    #       choco install gh -y
-    #     shell: cmd
+        # Install required tools
+      - name: Install NASM and GH
+        run: |
+          choco install nasm -y
+          choco install gh -y
+        shell: cmd
 
-    #   - name: Setup Visual studio
-    #     uses: microsoft/setup-msbuild@v2
+      - name: Setup Visual studio
+        uses: microsoft/setup-msbuild@v2
 
-    #   - name: Extract and increment version number
-    #     id: increment_version
-    #     run: |
-    #       $filePath = "CMakeLists.txt"
-    #       $version_line = Select-String -Path $filePath -Pattern 'set\(MOD_VERSION "(.*)"\)'
-    #       if ($version_line -match 'set\(MOD_VERSION "(\d+)\.(\d+)\.(\d+)"\)') {
-    #         $major = [int]$matches[1]
-    #         $minor = [int]$matches[2]
-    #         $patch = [int]$matches[3]
+        # Bump up the version number
+      - name: Extract and increment version number
+        id: increment_version
+        run: |
+          $filePath = "mod/CMakeLists.txt"
+          $version_line = Select-String -Path $filePath -Pattern 'set\(MOD_VERSION "(.*)"\)'
+          if ($version_line -match 'set\(MOD_VERSION "(\d+)\.(\d+)\.(\d+)"\)') {
+            $major = [int]$matches[1]
+            $minor = [int]$matches[2]
+            $patch = [int]$matches[3]
 
-    #         # Increment the minor version
-    #         $new_patch = $patch + 1
-    #         $new_version = "$major.$minor.$new_patch"
+            # Increment the minor version
+            $new_patch = $patch + 1
+            $new_version = "$major.$minor.$new_patch"
 
-    #         # Update the CMakeLists.txt file
-    #         (Get-Content $filePath) -replace 'set\(MOD_VERSION ".*"\)', "set(MOD_VERSION `"$new_version`")" | Set-Content $filePath
+            # Update the CMakeLists.txt file
+            (Get-Content $filePath) -replace 'set\(MOD_VERSION ".*"\)', "set(MOD_VERSION `"$new_version`")" | Set-Content $filePath
 
-    #         echo "NEW_VERSION=$new_version" >> $env:GITHUB_ENV
-    #         echo "FILE_PATH=$filePath" >> $env:GITHUB_ENV
-    #       } else {
-    #         Write-Error "Version line not found or does not match the expected format."
-    #         exit 1
-    #       }
-    #     shell: pwsh      
+            echo "NEW_VERSION=$new_version" >> $env:GITHUB_ENV
+            echo "FILE_PATH=$filePath" >> $env:GITHUB_ENV
+          } else {
+            Write-Error "Version line not found or does not match the expected format."
+            exit 1
+          }
+        shell: pwsh      
 
-    #   - name: Push bumped version
-    #     run: |
-    #       git config user.name "github-actions[bot]"
-    #       git config user.email "github-actions[bot]@users.noreply.github.com"
-    #       git add $env:FILE_PATH
-    #       git commit -m "Bump version to $env:NEW_VERSION"
-    #       git push
-    #     env:
-    #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-    #     shell: pwsh
+      - name: Push bumped version
+        run: |
+          git config user.name "github-actions[bot]"
+          git config user.email "github-actions[bot]@users.noreply.github.com"
+          git add $env:FILE_PATH
+          git commit -m "Bump version to $env:NEW_VERSION"
+          git push
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        shell: pwsh
 
-    #   - name: Build AmethystRuntime
-    #     run: |
-    #       mkdir build
-    #       cd build
-    #       cmake -DCI_CD_BUILD=ON ..
-    #       msbuild Amethyst.sln
+      - name: Build AmethystRuntime
+        run: |
+          mkdir build
+          cd build
+          cmake -DCI_CD_BUILD=ON ..
+          msbuild Amethyst.sln
 
     #   - name: Package Build
     #     run: |
